### ISSUE TITLE
请问下这个我收到通知有时候不显示消息内容

### ISSUE THREAD

**Issue by leeseean** [lilongweidev/NotifyListenerDemo#1]
我收到通知有时候不显示消息内容，只显示时间和包名，是什么问题呢。
可以把所有通知对象的字段都展示出来吗，可能取错了字段

**Comment by leeseean** [comment]
notification不能获取支付宝收款的金额，有办法展示出来吗

**Comment by lilongweidev** [comment]
你可以打印返回的数据看看，有什么。




Li
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lilongweidev/NotifyListenerDemo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月1日(星期六) 晚上7:06
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[lilongweidev/NotifyListenerDemo] 请问下这个我收到通知有时候不显示消息内容 (Issue #1)





 
我收到通知有时候不显示消息内容，只显示时间和包名，是什么问题呢。
 可以把所有通知对象的字段都展示出来吗，可能取错了字段

**Comment by leeseean** [comment]
> 你可以打印返回的数据看看，有什么。 Li ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "lilongweidev/NotifyListenerDemo" ***@***.***&gt;; 发送时间:&nbsp;2023年7月1日(星期六) 晚上7:06 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[lilongweidev/NotifyListenerDemo] 请问下这个我收到通知有时候不显示消息内容 (Issue #1) 我收到通知有时候不显示消息内容，只显示时间和包名，是什么问题呢。 可以把所有通知对象的字段都展示出来吗，可能取错了字段 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

打印了就是没有收款金额啊，只是提示只有一笔收款，具体多少金额没有
